spring:
  application:
    name: customer-accounts-transactions
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:db}
    username: ${DB_USERNAME:dbuser}
    password: ${DB_PASSWORD:dbpass}
  flyway:
    enabled: false
  profiles:
    active: "@spring.profiles.active@"
  jpa:
    hibernate:
      ddl-auto: update